Repository brave/adblock-lists, pull requests merged in 2020-03, with the labels that each got.

#344 Fixing https://github.com/brave/brave-browser/issues/8477 (WIP)
  brave-unbreak.txt
Labels: Brave List Issue

#346 Fixes https://sweeps.gg/giveaways/msi-trident-x-plus-gaming-pc-giveaway-2/
  brave-unbreak.txt
Labels: Disconnect List Issue

#345 Fix https://suumo.jp/ on IOS
  brave-unbreak.txt
Labels: ios specific

#348 Fixes http://pubnooks.com/
  brave-unbreak.txt
Labels: Desktop specific, Disconnect List Issue, android specific

#349 Remove redirect badfilter, as we support scriptlet redirects now
  brave-unbreak.txt
Labels: Brave List Issue

#350 Fixes https://www.crave.ca/
  brave-unbreak.txt
Labels: Disconnect List Issue

#351 Fix ads on https://mail.ru/
  brave-unbreak.txt
Labels: cosmetic, regional, revisit, wait for ubo resources

#354 Stop Weather.com Your privacy dialog box:
  brave-unbreak.txt
Labels: consents, revisit

#356 Fixes brave/brave-browser#8866
  brave-unbreak.txt
Labels: Disconnect List Issue

#353 Fix https://ca.yahoo.com/
  brave-unbreak.txt
Labels: ios specific

#357 Fix doubleclick.net clickthroughs
  brave-unbreak.txt
Labels: ios specific

#358 Adjust usps.com tracking filter for ios to be more specific
  brave-unbreak.txt
Labels: ios specific

#360 Fix Anti-adblock issues on pandora.com
  brave-unbreak.txt
Labels: anti-adblock

#359 Fix mailchimp images
  brave-unbreak.txt
Labels: Disconnect List Issue
