Repository brave/adblock-lists, pull requests merged in 2021-07, with the labels that each got.

#611 Fix rp5.ru anti-adblock
  brave-unbreak.txt
Labels: Desktop specific, uBO-redirect-rule

#612 Fixes anti-adblock on photopea.com
  brave-unbreak.txt
Labels: Desktop specific, uBO-redirect-rule

#613 Fix anti-adblock on shineads.in
  brave-unbreak.txt
Labels: Desktop specific, anti-adblock, uBO-redirect-rule

#615 Fixes https://github.com/brave/adblock-lists/issues/614
  brave-unbreak.txt
Labels: Strict Blocking

#616 Fixes blank space issues on various radio sites
  brave-unbreak.txt
Labels: Desktop specific, uBO-redirect-rule, webcompat

#618 Fix Anti-Brave on kodekloud.com
  brave-unbreak.txt
Labels: Brave List Issue, Desktop specific

#617 Fix https://github.com/AdguardTeam/AdguardFilters/issues/85641
  brave-lists/brave-specific.txt
Labels: Brave List Issue, Desktop specific, webcompat

#619 Fix portscanning perf issues on cibc.com
  brave-unbreak.txt
Labels: Localhost, Update existing Filters, perf

#620 Fix feedback url on search.brave.com
  brave-unbreak.txt
Labels: Brave List Issue
