Repository brave/adblock-lists, pull requests merged in 2022-05, with the labels that each got.

#843 Add t.umblr.com debounce
  brave-lists/debounce.json
Labels: Debounce

#846 Remove livemint snippet filter
  brave-unbreak.txt
Labels: cleanup

#847 Restore snippets from https://github.com/brave/adblock-lists/pull/844
  brave-unbreak.txt
Labels: Brave List Issue

#849 Fixes anti-adblock on jojo-themes.net
  brave-unbreak.txt
Labels: anti-adblock, Brave List Issue, uBO-redirect-rule

#850 Fixes userlytics.com navigator.connection checks
  brave-unbreak.txt
Labels: navigator.connection

#851 Adjust https://github.com/brave/adblock-lists/pull/850
  brave-unbreak.txt
Labels: cleanup, navigator.connection

#852 Remove unused duckduckgo exception
  brave-unbreak.txt
Labels: cleanup, Brave List Issue

#853 Cleanups for Brave unbreak
  brave-unbreak.txt
Labels: cleanup, Brave List Issue

#854 Update uBO-Annoyances Anti-ad commits
  brave-unbreak.txt
Labels: cleanup, uBO-Annoyances

#855 Fixes imagetotext.info anti-adblock
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#856 Include EasyDutch Anti-Adblock.txt
  brave-unbreak.txt
Labels: anti-adblock

#857 Removes redundant filters
  brave-unbreak.txt
Labels: cleanup

#858 Update kissanime/kimcartoon/kissasian mirrors
  brave-unbreak.txt
Labels: anti-adblock, cleanup, uBO-redirect-rule, uBO-domain-wildcard

#859 FIxes kitguru.net anti-adblock
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#860 Add bing trackers to first-party
  brave-lists/brave-firstparty.txt
Labels: First-party Trackers

#861 Add adservers from https://animixplay.to/
  brave-lists/brave-ios-specific.txt
Labels: ios specific

#862 Remove bouncers likely to have security benefits
  brave-lists/debounce.json
Labels: Debounce

#869 Temporarily remove unsupported rules
  brave-lists/debounce.json
Labels: Debounce

#872 Fix anti-adblock on https://www.uploadbank.com/
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#873 Fix performance on betfair.com
  brave-unbreak.txt
Labels: Localhost, perf

#874 Fixes anti-adblock on https://sprintally.com/
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#875 Fixes ubo-redirect on lineups.fun,13tv.co.il
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#876 Fixes anti-adblock on mangawt.com
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule
