Repository brave/adblock-lists, pull requests merged in 2022-10, with the labels that each got.

#980 Fix https://thememypc.net/
  brave-unbreak.txt
Labels: uBO-redirect-rule

#981 Test Twitch rule bravefix exception
  brave-unbreak.txt
Labels: Brave List Issue

#983 Fixes Anti-adblock on https://ckk.ai/ugLM7nx
  brave-unbreak.txt
Labels: cosmetic, anti-adblock

#984 Fixes Anti-brave checks on https://zoro.to/
  brave-unbreak.txt
Labels: anti-adblock, Brave List Issue

#978 Add Yahoo referrer tags
  brave-lists/clean-urls.json
Labels: Clean URLS

#989 Fix anti-ad on https://gpfans.org/
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#985 fix Anti-brave check on musenboya.com
  brave-unbreak.txt
Labels: anti-adblock, Brave List Issue

#992 Add URL junk to clean
  brave-lists/clean-urls.json
Labels: Clean URLS

#994 Debounce ActiveCampaign domains
  brave-lists/debounce.json
Labels: Debounce

#995 Fixes anti-adblock on https://photosonic.writesonic.com/
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#996 Fix admiral anti-adblock. Converted to redirect
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule

#998 Fixes empty spaces on arstechnica.com
  brave-unbreak.txt
Labels: standard-shields

#999 Improve cnn.com page display
  brave-unbreak.txt
Labels: standard-shields

#1000 Fixes empty space on forbes.com
  brave-unbreak.txt
Labels: standard-shields

#1001 Adjust to cover more than body
  brave-unbreak.txt
Labels: cleanup, standard-shields

#1002 Fixes anti-adblock elrellano.com
  brave-unbreak.txt
Labels: anti-adblock, uBO-redirect-rule
