Repository brave/adblock-lists, pull requests merged in 2022-12, with the labels that each got.

#1028 Fixes cnet.com adblock header
  brave-unbreak.txt
Labels: standard-shields

#1029 Add updated rd.bizrate.com
  brave-lists/debounce.json
Labels: Debounce

#1030 Fixes reuters.com empty space
  brave-unbreak.txt
Labels: standard-shields

#1031 Fix empty spaces on cultofmac.com
  brave-unbreak.txt
Labels: standard-shields

#1033 Fix regex filters on animixplay.to
  brave-unbreak.txt
Labels: regex

#1034 Add animepahe.ru regex
  brave-unbreak.txt
Labels: regex

#1032 Add MailerLite parameters
  brave-lists/clean-urls.json
Labels: Clean URLS

#1036 Fix gap.com page unresponsive issues
  brave-unbreak.txt
Labels: perf

#1037 Add Brave specific cookie list
  brave-lists/brave-cookie-specific.txt
Labels: consents, Cookie list

#1038 Fix cookie check on pepper.pl
  brave-lists/brave-cookie-specific.txt
Labels: consents, Cookie list

#1039 Update anti-brave fixes
  brave-unbreak.txt
Labels: cleanup

#1040 Fixes mydeals cooie requirements
  brave-lists/brave-cookie-specific.txt
Labels: Cookie list

#1041 Fixes anti-brave on https://9anime.vc/
  brave-unbreak.txt
Labels: Brave List Issue

#1042 Fixes cosmetic checks on cultura-informatica.com
  brave-unbreak.txt
Labels: cosmetic

#1043 Include more cookie from ADG
  brave-lists/brave-cookie-specific.txt
Labels: Cookie list

#1044 Fix nxbrew.com ads
  brave-unbreak.txt
Labels: regex

#1045 Update kissanime sites
  brave-unbreak.txt
Labels: anti-adblock, cleanup, uBO-domain-wildcard

#1046 Fixes snap.com cookie message
  brave-lists/brave-cookie-specific.txt
Labels: Cookie list

#1048 Fix igg-games.com (reported)
  brave-unbreak.txt
Labels: regex

#1049 fix rbs.ta36.com anti-adb
  brave-unbreak.txt
Labels: regional

#1050 Fixes signin issue with blockclubchicago.org (ios)
  brave-lists/brave-ios-specific.txt
Labels: ios specific

#1051 Fixes ratemyprofessors.com cookie message
  brave-lists/brave-cookie-specific.txt
Labels: Cookie list

#1052 Fix anti-adblock for comoapple.com
  brave-unbreak.txt
Labels: cosmetic, anti-adblock

#1053 Update uBO Anti-advert Annoyances
  brave-unbreak.txt
Labels: anti-adblock, uBO-Annoyances

#1054 Add Cookie check ebilet.pl
  brave-lists/brave-cookie-specific.txt
Labels: Cookie list
