Repository brave/adblock-lists, pull requests merged in 2023-02, with the labels that each got.

#1070 Filter a few Amazon URL decorations
  brave-lists/clean-urls.json
Labels: Clean URLS

#1072 Update google signin popups
  brave-unbreak.txt
Labels: google-login-nag

#1073 Add some custom :has supported filters
  brave-unbreak.txt
Labels: cosmetic

#1071 Exempt the Twitter redirector from URL modification
  brave-lists/clean-urls.json
Labels: webcompat, Clean URLS

#1074 Fixes forced google login for dashboard.razorpay.com
  brave-unbreak.txt
Labels: google-login-nag

#1076 Add Youtube specific lists
  brave-lists/yt-distracting.txt
  brave-lists/yt-recommended.txt
Labels: youtube additions

#1077 Add YT Distractions
  brave-lists/yt-distracting.txt
Labels: youtube additions

#1083 Update uBO Antiadblock
  brave-unbreak.txt
Labels: uBO-Annoyances

#1080 Medium email campaign source qs remove
  brave-lists/clean-urls.json
Labels: Clean URLS

#1085 Debounce backerkit email links
  brave-lists/debounce.json
Labels: Debounce

#1084 Clean Kickstarter and Reddit URLs
  brave-lists/clean-urls.json
Labels: Clean URLS

#1087 Add YT recommended additions
  brave-lists/yt-recommended.txt
Labels: youtube additions

#1090 Remove whathifi fixes
  brave-unbreak.txt
Labels: cleanup

#1092 Removed megaup anti-adblock filter
  brave-unbreak.txt
Labels: cleanup
